# @dotenv .env

### Получить структуру репозитория
GET http://127.0.0.1:8000/repos/FastAPI_Project/structure
Authorization: Bearer {{GITHUB_TOKEN}}

### Получить содержимое файла
GET http://127.0.0.1:8000/repos/FastAPI_Project/file?path=README.md
Authorization: Bearer {{GITHUB_TOKEN}}

### Создать новый файл
POST http://127.0.0.1:8000/repos/FastAPI_Project/file
Authorization: Bearer {{GITHUB_TOKEN}}
Content-Type: application/json

{
  "path": "app",
  "filename": "hello.txt",
  "content": "Привет, Boomerang!",
  "message": "Add hello.txt"
}
